# Generated by Django 3.1.2 on 2020-10-25 12:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created',)},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
