# Generated by Django 3.1.2 on 2020-11-11 13:49

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='departament',
            field=models.CharField(choices=[('D', 'Development'), ('M', 'Marketing'), ('H', 'HR'), ('L', 'Legal'), ('F', 'Finances'), ('O', 'Others')], default='D', max_length=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_public',
            field=models.BooleanField(default=False, help_text='If you check this, anyone will be able to see and comment in your task.'),
        ),
        migrations.AlterField(
            model_name='task',
            name='responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
    ]
