# Generated by Django 3.1.2 on 2020-10-27 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0002_auto_20201025_1355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('created',)},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('-date_created',)},
        ),
    ]
