# Generated by Django 3.1.2 on 2020-10-27 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0003_auto_20201027_1652'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('due_date',)},
        ),
    ]
